### ISSUE TITLE
build docker container for armv6?

### ISSUE THREAD

**Issue by twochannel** [OpenZWave/qt-openzwave#102]
Will the arm architecture docker container work for an armv6 raspberry pi (rpi model rev2)?
I'm getting errors when trying to run the image either with docker run or docker-compose.

```failed to resize tty, using default size```

googling points to an architecture mismatch.

If not, can this arch be supported?

**Comment by Fishwaldo** [comment]
I don't own any Pi's that old, and just tried to do a cross compile for armv6 - After 4 hours it go killed with a out of memory error... 

So I think you will have to stick with the HA addon version

**Comment by twochannel** [comment]
Thanks for trying!  It's time to retire this thing.
