### ISSUE TITLE
Yale Touchscreen Deadbolt (YRD446) not updating status

### ISSUE THREAD

**Issue by DelusionalAI** [OpenZWave/qt-openzwave#105]
When manually activating the deadbolt by any local means, (key, inside knob, or the keypad), the QT-Openzwave doesn't update the lock status until it is polled again. The event logs do show show the Values labeled "Access Control, Alarm Type, and Alarm level" changing with the status of the lock, but not values "Locked" or "Locked (Advanced)" Home Assistant doesn't show the correct status of the lock until it is polled as a result.

The same issue showed up when I used Zwave2mqtt, but not when I was using the ZWave native to Home Assistant, so I'm not sure if the issue is related or Openzwave 1.6 or the way the lock itself functions.

**Comment by towerhand** [comment]
Thanks for creating this issue, I have this lock and it’s behaving the same with zwave2mqtt, I was going to migrate to qtozw to test so you saved me the time and effort.

**Comment by Fishwaldo** [comment]
It probably needs the same fixes as seen in this PR:
https://github.com/OpenZWave/open-zwave/pull/2256/files

Please test and open a PR for your config file if indeed it does work.

**Comment by DelusionalAI** [comment]
Looks like you were right, that fixed the issue. Made a pull request upstream.

https://github.com/OpenZWave/open-zwave/pull/2260
