### ISSUE TITLE
Persist ozw-admin settings (allinone image)

### ISSUE THREAD

**Issue by kpine** [OpenZWave/qt-openzwave#111]
It looks like the ozw-admin settings file is saved in `/root/.config/OpenZWave/ozw-admin.conf`. If you follow the docker example instructions this path is not specified as a volume, so once you re-create the container you will lose the settings.

Is the path configurable in ozw-admin? If so, should the allinone image modify the path to default it to something like the USER directory (or a subdir of that)? Or are users responsible for configuring their own persistent volume, and so the docker examples should be updated, e.g. `-v $PWD/ozwd/ozw-admin:/root/.config/OpenZWave`?

**Comment by kpine** [comment]
Alternatively, exposing some of the settings via environment variables? Specifically, I was looking at the Network Object Cache setting.

**Comment by davidkaplan** [comment]
same issue here.  Network Object Cache does not persist between sessions.
