### ISSUE TITLE
ozw-admin segfault (Sig=11) on hassio vdi, intel

### ISSUE THREAD

**Issue by Madelaide** [OpenZWave/qt-openzwave#112]
I have hassio running on virtual box, using the latest vdi, and expanded to 15G - so that the updates work instead of the disk filling.

Using openzwave admin, I change some settings on Zwave device (like beep disable) or wallmote, I can't see anyway to save the changes except "close ozwadmin" , and when I do this, nothing seems to happen, but I see this segv in the log (dmesg). I can't copy paste the text, so took a screengrab to attach.

![Annotation 2020-06-19 115848](https://user-images.githubusercontent.com/10949835/85090507-73d30f00-b224-11ea-9cac-419e96fbb9ac.png)

arch | x86_64
-- | --
chassis | vm
dev | false
docker | true
docker_version | 19.03.8
hassio | true
host_os | HassOS 4.10
installation_type | Home Assistant
os_name | Linux
os_version | 5.4.44
python_version | 3.7.7
supervisor | 227
timezone | Australia/
version | 0.111.4
virtualenv | false

PS: awesome work with this zwave library!

**Comment by Madelaide** [comment]
Can I move this issue to OpenZWave/ozw-admin ?

**Comment by Fishwaldo** [comment]
Unfortuantly I need proper log files about the crash - a Kernel message doesn't help at all.

**Comment by Madelaide** [comment]
Sure, I will try and get it off with smb, this file ->home-assistant.log in config?

Is there a debug level for a specific component i should add to the "logger:"?

PS: I did not see a core file; they used to help me find the offending call. Is there an option to enable these if it is a C object?

**Comment by Madelaide** [comment]
Attached is  a fresh log from the test vm, with logger set to debug
The console crashed at the same point as the screenshot originally posted following a vm restart.

[home-assistant.orig20200622.log](https://github.com/OpenZWave/qt-openzwave/files/4810820/home-assistant.orig20200622.log)

**Comment by Fishwaldo** [comment]
Unfortunately that’s the HA log that does not contain any logs related to OZW-admin. 

Several releases have been made recently. Can you try the standalone version of OZW-admin please.

**Comment by Madelaide** [comment]
Sorry, that was the only log I could find via SMB in the config folder.

When you say, "standalone version", do you mean a docker instance? like 
`docker run -it --security-opt seccomp=unconfined --device=/dev/ttyUSB0 -v /tmp/ozw:/opt/ozw/config -e MQTT_SERVER="10.100.200.102" -e USB_PATH=/dev/ttyUSB0 --network host openzwave/ozwdaemon:latest`

If, so, I will try and get it going - If i could can run the above from the hassio vm then I should be able to do it today sometime (local time 731 am, Tuesday)

**Comment by Madelaide** [comment]
well the above did work, but probably wasn't what you were asking for. I stumbled across the ozwadmin release app (which I didnt even know existed) and ran that - connection refused - I'm not sure what "authentication key" to use, I tried the HA password, but no. (I also tried vnc client to ports 5900 and 7800, but also conneciton refused - without asking for credentials)

I'm not even sure if this is going in the right direction as the crash shown intially is in libqvnc.so library and the separate ozwadmin instance won't fix that, but I guess it might confirm if I can save and edit the nodes properly.

**Comment by Madelaide** [comment]
Worked it out, the "host" is not a host ip, but the port number, 1983, which is already on the UI, so somewhat confusing. And so no "authentication key" is required for it to work.

That done, it connected, but said it was the "wrong version" for the daemon.

So I connected with vnc on port 5900, and that DID allow me to change settings on my test devices., and it DID show events inthe "event list" which the built-in UI did not.

The VNC connection did NOT show all the "product" names, but still allowed their selection and settings to be modofied.

**Comment by Madelaide** [comment]
V0.5.0 has the same segfault during system start

**Comment by Madelaide** [comment]
Ozw dead. Closing.
