### ISSUE TITLE
Add NodeApplicationVersion to Node Payload

### ISSUE THREAD

**Issue by DelusionalAI** [OpenZWave/qt-openzwave#123]
The value is can be viewed in OZWAdmin, but is only published to the node/commandclass/134. 
The goal is to allow viewing the firmware version of a device in HA (Once python-openzwavemqtt and the HA/ozw integration are updated to pull this info of course)

**Comment by Fishwaldo** [comment]
I don't think I'll implement this - The information is already available under the topic you have posted. The Gui's (front ends) can pull this topic information without having to "republish" the information. Maybe you can open a issue on the ozw-admin repo to ask the Version information be published in the DeviceInfo Tab as well.

**Comment by DelusionalAI** [comment]
The Node payload seemed like a natural place for firmware version which is why I opened the issue, but you are right it redundant . I'll see about getting that info into the HA ozw integration from commandclass 134 and the the open an issue in ozw-admin for the device info tab. 
Thanks for considering it!
