### ISSUE TITLE
Stuck at "Waiting for the Controller to Enter AddNode Mode..."

### ISSUE THREAD

**Issue by MTrab** [OpenZWave/qt-openzwave#130]
I have setup ozw-daemon in Docker on my Synology NAS, as that's where the dongle is connected.
But when trying to Add Node, all I get is a window saying `Starting...` and in details it says `Waiting for the Controller to Enter AddNode Mode...`

I don't see anything being logged by Docker and I can't see any other log files.

I used this little script to create the container on my Synology:

```
#!/usr/bin/bash
export IMAGE=openzwave/ozwdaemon:allinone-latest
export DNAME=OpenZWave
docker stop $DNAME
docker rm $DNAME && \
docker pull $IMAGE && \
docker create --security-opt seccomp=unconfined \
           --device=/dev/ttyACM1 \
           -v /volume2/docker/OpenZWave/ozw:/opt/ozw/config \
           -e MQTT_SERVER="10.254.xxx.yyy" \
           -e MQTT_USERNAME="MY_HIDDEN_USER" \
           -e MQTT_PASSWORD="MY_HIDDEN_PASSWORD" \
           -e OZW_NETWORK_KEY="MY_HIDDEN_KEY" \
           -e USB_PATH=/dev/ttyACM1 \
           -p 1983:1983 \
           -p 5901:5901 \
           -p 7800:7800 \
           --name $DNAME \
           $IMAGE && \
docker start $DNAME
```

What to do?

**Comment by Fishwaldo** [comment]
Your Logs will be in /volume2/docker/OpenZWave/ozw/logs/ozwdaemon/

Please have a look there to see whats going on, and upload here if you can't figure it out.

**Comment by MTrab** [comment]
After a complete restart  of Synology and containers it's working. Althou it's not forwarding new states to Home Assistant.
I'll investigate this a bit more, and if I can't solve it I'll open a new issue on that part.
