### ISSUE TITLE
Honeywell T6 Pro thermostat reports set points in celsius units

### ISSUE THREAD

**Issue by joshtbernstein** [OpenZWave/qt-openzwave#131]
Similar to https://github.com/OpenZWave/qt-openzwave/issues/117, I'm having issues with the units on my Honeywell T6 Pro thermostat. The set points are reported in fahrenheit but the units are reported as celcius. This is causing issues with Home Assistant as it shows a cooling set point of 76F as 168.8F (76C converted to F). I was previously using from Home Assistant's legacy builtin zwave integration which did not have this issue.

**Comment by Fishwaldo** [comment]
Merging with #117
