### ISSUE TITLE
[question] Execute Commands using an MQTT Explorer

### ISSUE THREAD

**Issue by varet80** [OpenZWave/qt-openzwave#30]
Hi All,

Trying to execute commands using MQTT Explorer. I am publishing topics for commands like: addNode or removeNode but I do see nothing happening.

As I am pretty new to MQTT and probably I am doing something wrong I am asking for help.
reading the spec https://github.com/OpenZWave/qt-openzwave/blob/master/docs/MQTT.md (which probably I am not reading properly) 

I did publish the following topics:

Topic OpenZWave/1/command/addNode/
payload: { "secure": false }

Topic: OpenZWave/1/command/removeNode/
payload: { } (or empty)

I do see no reactions from the z-wave or qt-openzwave. What am I doing wrong?

**Comment by varet80** [comment]
Found the mistake. the use of capital letters.

publishing lowercase did the trick

**Comment by chilicheech** [comment]
Documentation should specify that the commands should be lowercase. For instance, the documentation mentions the `setValue` topic. The topic is actually `setvalue`. It took me a long time to finally stumble across this being documented in this github issue.
