### ISSUE TITLE
Build error - qmake

### ISSUE THREAD

**Issue by JumpMaster** [OpenZWave/qt-openzwave#46]
Hi,

After clone the repository and running the following from the root directory I receive the below error.

docker build -t qt-openzwace Docker/

Step 10/32 : COPY . /opt/qt-openzwave/
 ---> cbe5157b16b6
Step 11/32 : RUN cd qt-openzwave && if [ -f Makefile ]; then /usr/lib/qt5/bin/qmake -r; make distclean; fi && /usr/lib/qt5/bin/qmake -r "CONFIG+=BreakPad" &&  make -j4 && make install
 ---> Running in b1f6678d2158
Usage: /usr/lib/qt5/bin/qmake [mode] [options] [files]

I would like to add mqtt authentication and offer a pull request.  I need to get it building first though :)

**Comment by Fishwaldo** [comment]
Wrong command. It should be:
```
docker build . -f Docker/Dockerfile -t <tag>
```
