### ISSUE TITLE
Add docker-compose description

### ISSUE THREAD

**Issue by nicklaseklund** [OpenZWave/qt-openzwave#50]
Add description on how to run it with docker-compose (including Network Key).

**Comment by JumpMaster** [comment]
version: '3'
services:
  qt-openzwave:
    image: openzwave/ozwdaemon:latest
    container_name: "qt-openzwave"
    security_opt:
      - seccomp:unconfined
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    volumes:
      - /home/ozw/config:/opt/ozw/config
    environment:
      MQTT_SERVER: "192.168.0.1"
      MQTT_USERNAME: "my-username"
      MQTT_PASSWORD: "my-password"
      USB_PATH: "/dev/ttyUSB0"
      OZW_NETWORK_KEY: "0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00"
    restart: unless-stopped

**Comment by nicklaseklund** [comment]
Thanks, have verified that it is working good (Except for MQTT user/pass because it is unauthorized).

**Comment by JumpMaster** [comment]
Only used MQTT_USERNAME and MQTT_PASSWORD if you have configured authentication.  Also change the OZW_NETWORK_KEY to your own key value.

**Comment by Fishwaldo** [comment]
PR welcome

**Comment by nicklaseklund** [comment]
PR created https://github.com/OpenZWave/qt-openzwave/pull/55

Edit: sanity check failed. Looks like it fails when trying to fetch something for the check itself. It fails to clone something from chromium. I don't see any option to re-run the build. Maybe only repository owner is allowed to re-run?

**Comment by Fishwaldo** [comment]
Yeah, the Github Actions sometimes has issues. Rerunning the check now, see if its a perm error or temporary error.
