### ISSUE TITLE
Hass.io add-on

### ISSUE THREAD

**Issue by uSpike** [OpenZWave/qt-openzwave#53]
Hi, just wondering if the maintainers would be open to merging support for a custom [hass.io addon](https://developers.home-assistant.io/docs/hassio_addon_tutorial)?  I'm not sure if this is the right place for it, otherwise I'd start a new repository if there isn't one already and request that the `README` be updated with a link.

**Comment by Fishwaldo** [comment]
There already is. It’s slowing being developed and very betaish right now. Cgarwood is leading that effort.

**Comment by uSpike** [comment]
@Fishwaldo do you mean https://github.com/cgarwood/homeassistant-zwave_mqtt ?

It is my understanding that `homeassistant-zwave_mqtt` is a home-assistant component that  requires this project (`qt-openzwave`) to be running a daemon (in a docker container).  My proposal in this issue is to create a hass.io addon which runs the `qt-openzwave` daemon.

**Comment by uSpike** [comment]
Nevermind, I see that there's already a hass.io add-on here: https://github.com/marcelveldt/hassio-addons-repo/tree/master/ozwdaemon
