### ISSUE TITLE
Cannot get docker image to run due to missing  libQt5Test.so.5

### ISSUE THREAD

**Issue by raz0rf0x** [OpenZWave/qt-openzwave#56]
I was trying to load and run a docker container and was met with
`/usr/local/bin/ozwdaemon: error while loading shared libraries: libQt5Test.so.5: cannot open shared object file: No such file or directory`

Currently running docker on Ubuntu 16.04.6 LTS. Making sure everything is as upgraded as it can be and will keep trying. Any help in figuring out what I'm missing would be appreciated.

**Comment by kpine** [comment]
I see this as well. Looks like ozwdaemon now depends on libQt5Test.so, when it didn't before.

**Comment by kpine** [comment]
`openzwave/ozwdaemon:build-65` is the last image working for me.

**Comment by raz0rf0x** [comment]
> `openzwave/ozwdaemon:build-65` is the last image working for me.

Same here. 65 works for me as well

**Comment by Fishwaldo** [comment]
New Image building now. Should be available in a few hours
