### ISSUE TITLE
Unable to build from Dockerfile

### ISSUE THREAD

**Issue by quinnhosler** [OpenZWave/qt-openzwave#64]
I appear to be unable to build from the dockerfile in this repository. I receive an error on this section of code. It appears that qmake is not receiving the correct arguments. I experimented but was unable to find a solution and am unfamiliar with qmake. I failed to build from the file on two seperate machines with the same error. 

```
RUN cd qt-openzwave \
	&& if [ -f Makefile ]; then /usr/lib/qt5/bin/qmake -r; make distclean; fi \
	&& /usr/lib/qt5/bin/qmake -r "CONFIG+=BreakPad" \
	&&  make -j4 \
	&& make install
```

I have not experienced problems with the openzwave/ozwdaemon:latest image. However, I do not know how often these images are built.

**Comment by kpine** [comment]
I am able to build the image. What is your build command?

```sh
docker build -t foo -f Docker/Dockerfile .
```

**Comment by quinnhosler** [comment]
Yeah, I was running a similar command with no dice. 

Today, though, I'm have a whole host of other issues connecting to the deb.debian.org repos with docker and the ubuntu repos on my own machine. I managed to fix everything by forcing IPv6. I have no idea what's going on, and I don't know if this is a me or them problem. 

I'm going to go ahead and close this. As long as other people can build the image, that's all that matters.
