### ISSUE TITLE
Alternate install methods for FeeNAS/FreeBSD

### ISSUE THREAD

**Issue by tprelog** [OpenZWave/qt-openzwave#69]
Hello, thank you for your work. I have been running a small test system on a rpi 4 using the docker container with good success, however, I would eventually like ( _if it's possible_ ) to have `owzdaemon` running from my main FreeNAS server.

<s>So here's the curve ball, my server is running [FreeNAS](https://www.freenas.org/) ( based FreeBSD ) but there is no support for docker --  FreeNAS does includes the [bhyve hypervisor](https://bhyve.org/) but this does not support USB pass-through so a VM running Linux w/Docker will not work.

_Will there eventually be instructions for a "bare metal" install process?_

On FreeNAS, there is a similar container technology called [jails](https://www.ixsystems.com/documentation/freenas/11.3-U2/jails.html#jails). I would like to attempt a "bare metal" install to get qt-openwave running from a jail on my FreeNAS.
</s>
Thanks

**Comment by ktpx** [comment]
So, they expect docker install on PI's? (for those with razberry zwave boards).  Not very likely.

**Comment by tprelog** [comment]
With hints from the updated README and following the docker-file, I was able to get `ozwdaemon` running in an iocage jail FreeNAS 11.3

If anybody else wants to try this on FreeNAS or FreeBSD, here's a link to a quick run down and also a rc script to run ozwdaemon as a service.

https://github.com/tprelog/iocage-ozwdaemon/wiki

**Comment by Fishwaldo** [comment]
Closing this.
