### ISSUE TITLE
Docker image no longer building

### ISSUE THREAD

**Issue by kpine** [OpenZWave/qt-openzwave#72]
Maybe you're aware, but the image no longer builds due to what looks like updates to the unstable repository packages. Not sure if it's just a transient issue, if there is a workaround, or if they are now incompatible.
```
#8 [5/8] RUN apt-get -y -t unstable install qt5-default libqt5websockets5-d...
#8 0.413 Reading package lists...
#8 3.900 Building dependency tree...
#8 4.457 Reading state information...
#8 5.008 Some packages could not be installed. This may mean that you have
#8 5.008 requested an impossible situation or if you are using the unstable
#8 5.008 distribution that some required packages have not yet been created
#8 5.008 or been moved out of Incoming.
#8 5.008 The following information may help to resolve the situation:
#8 5.008
#8 5.008 The following packages have unmet dependencies:
#8 5.204  libc6-dev : Breaks: libgcc-8-dev (< 8.4.0-2~) but 8.3.0-6 is to be installed
#8 5.241 E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
#8 ERROR: executor failed running [/bin/sh -c apt-get -y -t unstable install qt5-default libqt5websockets5-dev qtbase5-private-dev libqt5remoteobjects5-dev libqt5remoteobjects5-bin]: buildkit-runc did not terminate sucessfully
```

**Comment by kpine** [comment]
FYI, it builds fine if you switch the base image entirely to bullseye-slim and remove all of the repository modifications. Bullseye has the same QT 5.12.5 packages that sid does. Not sure if you want to go that route though, since it will update the dev toolchain as well (gcc 10, etc.).

**Comment by Fishwaldo** [comment]
I've switch to Ubuntu Focal as that has the required deps without having to use unstable repos

**Comment by Fishwaldo** [comment]
FYI - Bloody Issues with RPI images now. I'm looking at workarounds for this.. will advise when I get it building again .

**Comment by kpine** [comment]
Are you having trouble with breakpad?

Trying removing wget and replacing it with curl.

**Comment by Fishwaldo** [comment]
No. With this issue:
https://github.com/moby/moby/issues/40734

**Comment by kpine** [comment]
Ahh, that does not sound good... Apparently, it only happens on native ARM hardware, https://github.com/osrf/multiarch-docker-image-generation/issues/38. I'm building the arm image on an amd64 host, which explains why I didn't encounter the same problem. Doubt it will actually run then.

Instead, I had an issue with `fetch` failing because of wget and SSL certificates. Just swapping it for curl worked. Makes no sense.

**Comment by Fishwaldo** [comment]
>Apparently, it only happens on native ARM hardware

Its actually a kernel version issue. The default kernel on rPI's is around 4.4 (from memory) but the Focal Release uses features from Kernel 5.5. It should gracefully fail and fall back. I *could* work around it and upgrade the kernel on the build hosts to 5.5, but I suspect it will still fail for users on the original 4.4 kernel. 

So following those threads to see which way it gets fixed (either in the seccomp library, docker, or ubuntu focal)

**Comment by iav** [comment]
`4.19.97-v7+ #1294 SMP Thu Jan 30 13:15:58 GMT 2020 armv7l GNU/Linux`
