### ISSUE TITLE
Device associations

### ISSUE THREAD

**Issue by anthonyangel** [OpenZWave/qt-openzwave#74]
It looks like setting up associations hasn't been implemented yet. Is this on the roadmap?

I'm trying to set up associations between some Fibaro FGD-212 dimmers, but can't find the functionality for that (it looks like it's a separate setting from a config parameter)

**Comment by kpine** [comment]
I have had success using the command.

https://github.com/OpenZWave/qt-openzwave/blob/master/docs/MQTT.md#addassociation

**Comment by Fishwaldo** [comment]
As @kpine mentioned - its a series of commands.
