### ISSUE TITLE
FR: Add Support for network attached USB stick

### ISSUE THREAD

**Issue by rbflurry** [OpenZWave/qt-openzwave#79]
I came here from the HA annouocment that this is the path forward for Zwave. Sorry if this is not approproite but I wanted to see if this was within your scope.

For the past 6 months I have been using a zwave stick that is attached to a mini wifi router located centrally in my house. Almost like my own Wink or Smart Things hub.

You can read more about it here. https://community.home-assistant.io/t/add-network-protocol-support-to-zigbee-and-zwave-integrations/136056

Could you see adding network support for this integration? My alternative could be to replace the wifi-router with a pi that can run this container, but the router is small, poe or usb powered and works perfectly.

Thank you for the time.

**Comment by Fishwaldo** [comment]
Others have tried, and not succeeded - See https://github.com/OpenZWave/Zwave2Mqtt/issues/243 for details. 

Only alternative that is known to work is use [usbip](https://wiki.archlinux.org/index.php/USB/IP)

**Comment by dvbit** [comment]
:-( unistalled everything too fast. I tried on a secondary pc. with dongle directly plugged and worked.
Installed in  my steady setup and it is not working as I have the stick mounted remotely on a raspberry and replicatred locally on /dev/zwave through remserver.
Please add it to the serial -> IP not working
