### ISSUE TITLE
README.md does not list prerequesites or give build instructions

### ISSUE THREAD

**Issue by gdt** [OpenZWave/qt-openzwave#85]
I'm trying to build this for NetBSD, via pkgsrc, and hence not using docker.  While I expect to figure it out just from reading sources, I noticed that README.md doesn't have the usual list of what other packages this depends on (qt5 base libs, openzwave ?), or give any build instructions.

Also, this seems to contain both ozwdaemon, which is an MQTT bridge, as well as some sort of "qt wrapper", and it's unclear what "qt wrapper" means.   It's also unclear whether one is meant only to be able to build all the things from this repo at once, or if there is a notion of subprojects.

**Comment by kpine** [comment]
In lieu of official build instructions, you can also just follow along the [Dockerfile](url). It literally defines all of the dependencies and build steps, so you could probably derive the dependencies NetBSD would need.

**Comment by Fishwaldo** [comment]
I've been focusing just on the Docker Image for HomeAssistant for now. I'll get to this officially soon. (someone is going to have a go at converting to cmake as well).

As mentioned by @kpine you can use the Dockerfile as a reference, but you could skip the depot_tools (as thats Google Breakpad - A crash handler) as that requires post-processing as well (and I don't want "unofficial builds" clogging up my crash reporting!!)

**Comment by Fishwaldo** [comment]
qt-openzwave is actually a [qt](qt.io) wrapper for OZW. qt-ozwdaemon is a application that talks to MQTT and allows remote access (for ozw-admin) that has a dependency upon qt-openzwave. qt-simpleclient (might not be building at the moment, I haven't tested it) is just a simple test of the wrapper

**Comment by Fishwaldo** [comment]
Some Basic Instructions are now provided.

**Comment by gdt** [comment]
Thanks - that helps a lot.   I had not figured out the bit about a specific QT version only, vs "at least X".
