### ISSUE TITLE
REQ: (re)store node names after restart 

### ISSUE THREAD

**Issue by posixx** [OpenZWave/qt-openzwave#89]
Currently when restarting the docker image the node names configured through ozw-admin are lost. This messes up home assistant  as these node names are used for sensor naming.

![image](https://user-images.githubusercontent.com/2280400/83120969-07a43600-a0d2-11ea-95a0-2da44c666e79.png)

Please make sure these names are stored, for instance in the cache file within the image.

**Comment by kpine** [comment]
This is a problem with the HA Addon, not qt-openzwave, likely related to #75. https://github.com/home-assistant/hassio-addons/issues/1361

Node names are saved as long as the cache file is persisted.

**Comment by foxy82** [comment]
I don't think it is HA - I think it is this qt-openzwave issue: https://github.com/OpenZWave/qt-openzwave/issues/75

The hassio add on sets a config path here: https://github.com/home-assistant/hassio-addons/blob/master/zwave/rootfs/etc/services.d/zwave/run but it is ignored.

**Comment by kpine** [comment]
My point was that the node names are being saved. The bug is related to cache persistence, so it is an easily avoided problem unless you are using the HA Addon.

If you lose the cache file, delete it or it gets corrupt, you're also going to lose the names.

**Comment by foxy82** [comment]
From the qt-openzwave bug report you might be able to work around this by running the HA Add on once your network is stable and you've renamed the lights log into the docker 
`sudo docker exec -it <container name> /bin/bash`

and then copying the files from /run/s6/services/zwave/config to the persistent storage partion - I think this is /data and then restart and see if the persistent storage is picked up.

I can't try this as I've moved to using the ozwdaemon docker instead.

**Comment by marcelveldt** [comment]
this issue should be solved by now with recent HA addon versions.
possible to confirm and/or close the issue @posixx ?

**Comment by alexgorbatchev** [comment]
I can confirm that this issues isn't related to HA. It happens with plain ozwdaemon running in docker and connecting via ozwadmin. I see node names are being lost on restart and after manually refreshing node info. I'm running version `0.1.74`
